version: '2'

services:
  # elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: elasticsearch
    environment:
      - cluster.name=cluster-vincent
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  # kibana  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.1
    container_name: kibana
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    ports:
     - 5601:5601
    networks:
      - esnet
    depends_on:
     - "elasticsearch"

volumes:
  esdata1:
    driver: local

networks:
  esnet:
